# Generated by Django 2.2.6 on 2021-07-21 14:35

import api.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210720_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('year', models.PositiveSmallIntegerField(validators=[api.validators.validate_year])),
                ('description', models.TextField(blank=True, max_length=1500, verbose_name='Описание')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_title', to='api.Category', verbose_name='Категория')),
                ('genre', models.ManyToManyField(related_name='genre_title', to='api.Genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Название произведения',
                'verbose_name_plural': 'Названия произведений',
            },
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-id'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.Title', verbose_name='Произведение'),
        ),
        migrations.DeleteModel(
            name='Titles',
        ),
    ]
