# Generated by Django 2.2.6 on 2021-07-21 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210721_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(
                blank=True,
                default=django.utils.timezone.now,
                unique=True,
                verbose_name='Категория slug',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(
                blank=True,
                default=django.utils.timezone.now,
                unique=True,
                verbose_name='Жанр slug',
            ),
            preserve_default=False,
        ),
    ]
